// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/scan": {
            "post": {
                "description": "Analyses a URL offline (the scanner never sends traffic to it) and returns a risk score, level and the reasons behind it. Repeat scans of the same normalized URL are served from the Redis cache.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "scans"
                ],
                "summary": "Scan a URL",
                "parameters": [
                    {
                        "description": "URL to scan",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_handler.ScanRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_neerajgurjar_goshield_backend_internal_model.Scan"
                        }
                    },
                    "400": {
                        "description": "INVALID_URL or INVALID_REQUEST",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.ErrorEnvelope"
                        }
                    },
                    "429": {
                        "description": "RATE_LIMIT_EXCEEDED",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.ErrorEnvelope"
                        }
                    },
                    "500": {
                        "description": "INTERNAL_SERVER_ERROR",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.ErrorEnvelope"
                        }
                    }
                }
            }
        },
        "/api/v1/scans": {
            "get": {
                "description": "Returns scans newest first, with optional filtering and paging.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "scans"
                ],
                "summary": "List scan history",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Page number, 1-based",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Page size, max 100",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "SAFE",
                            "LOW",
                            "MEDIUM",
                            "HIGH"
                        ],
                        "type": "string",
                        "description": "Filter by risk level",
                        "name": "risk_level",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "SAFE",
                            "SUSPICIOUS",
                            "BLOCKED"
                        ],
                        "type": "string",
                        "description": "Filter by status",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by exact domain",
                        "name": "domain",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Only scans created at or after this RFC3339 timestamp",
                        "name": "from",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Only scans created at or before this RFC3339 timestamp",
                        "name": "to",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.ListScansResponse"
                        }
                    },
                    "400": {
                        "description": "INVALID_REQUEST",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.ErrorEnvelope"
                        }
                    },
                    "429": {
                        "description": "RATE_LIMIT_EXCEEDED",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.ErrorEnvelope"
                        }
                    },
                    "500": {
                        "description": "INTERNAL_SERVER_ERROR",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.ErrorEnvelope"
                        }
                    }
                }
            }
        },
        "/api/v1/scans/bulk": {
            "post": {
                "description": "Scans a batch of URLs through a bounded worker pool. Results come back in input order; an entry that could not be scanned carries an error object instead of a scan, so one bad URL does not fail the batch.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "scans"
                ],
                "summary": "Scan up to 100 URLs",
                "parameters": [
                    {
                        "description": "URLs to scan, at most 100",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_handler.BulkScanRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.BulkScanResponse"
                        }
                    },
                    "400": {
                        "description": "INVALID_REQUEST",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.ErrorEnvelope"
                        }
                    },
                    "429": {
                        "description": "RATE_LIMIT_EXCEEDED",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.ErrorEnvelope"
                        }
                    },
                    "500": {
                        "description": "INTERNAL_SERVER_ERROR",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.ErrorEnvelope"
                        }
                    }
                }
            }
        },
        "/api/v1/scans/{id}": {
            "get": {
                "description": "Returns a single previously stored scan.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "scans"
                ],
                "summary": "Get a scan by id",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Scan id (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_neerajgurjar_goshield_backend_internal_model.Scan"
                        }
                    },
                    "404": {
                        "description": "SCAN_NOT_FOUND",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.ErrorEnvelope"
                        }
                    },
                    "429": {
                        "description": "RATE_LIMIT_EXCEEDED",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.ErrorEnvelope"
                        }
                    },
                    "500": {
                        "description": "INTERNAL_SERVER_ERROR",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.ErrorEnvelope"
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "description": "Liveness probe for the service.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "system"
                ],
                "summary": "Health check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.HealthResponse"
                        }
                    }
                }
            }
        },
        "/metrics": {
            "get": {
                "description": "In-memory counters in Prometheus text format.",
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "system"
                ],
                "summary": "Service metrics",
                "responses": {
                    "200": {
                        "description": "goshield_scans_total 1250",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "github_com_neerajgurjar_goshield_backend_internal_model.RiskLevel": {
            "type": "string",
            "enum": [
                "SAFE",
                "LOW",
                "MEDIUM",
                "HIGH"
            ],
            "x-enum-comments": {
                "RiskLevelHigh": "76-100",
                "RiskLevelLow": "21-50",
                "RiskLevelMedium": "51-75",
                "RiskLevelSafe": "0-20"
            },
            "x-enum-descriptions": [
                "0-20",
                "21-50",
                "51-75",
                "76-100"
            ],
            "x-enum-varnames": [
                "RiskLevelSafe",
                "RiskLevelLow",
                "RiskLevelMedium",
                "RiskLevelHigh"
            ]
        },
        "github_com_neerajgurjar_goshield_backend_internal_model.Scan": {
            "type": "object",
            "properties": {
                "cached": {
                    "type": "boolean",
                    "example": false
                },
                "created_at": {
                    "type": "string",
                    "example": "2026-08-31T10:00:00Z"
                },
                "domain": {
                    "type": "string",
                    "example": "example.com"
                },
                "id": {
                    "type": "string",
                    "example": "8f14e45f-ea2b-4c5d-9f1a-0d1b2c3d4e5f"
                },
                "normalized_url": {
                    "type": "string",
                    "example": "https://example.com/login"
                },
                "protocol": {
                    "type": "string",
                    "example": "https"
                },
                "reasons": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "Contains suspicious keyword: login"
                    ]
                },
                "risk_level": {
                    "enum": [
                        "SAFE",
                        "LOW",
                        "MEDIUM",
                        "HIGH"
                    ],
                    "allOf": [
                        {
                            "$ref": "#/definitions/github_com_neerajgurjar_goshield_backend_internal_model.RiskLevel"
                        }
                    ],
                    "example": "SAFE"
                },
                "risk_score": {
                    "type": "integer",
                    "example": 10
                },
                "safe": {
                    "type": "boolean",
                    "example": true
                },
                "scan_time_ms": {
                    "type": "integer",
                    "example": 4
                },
                "status": {
                    "enum": [
                        "SAFE",
                        "SUSPICIOUS",
                        "BLOCKED"
                    ],
                    "allOf": [
                        {
                            "$ref": "#/definitions/github_com_neerajgurjar_goshield_backend_internal_model.Status"
                        }
                    ],
                    "example": "SAFE"
                },
                "url": {
                    "type": "string",
                    "example": "https://example.com/login"
                }
            }
        },
        "github_com_neerajgurjar_goshield_backend_internal_model.Status": {
            "type": "string",
            "enum": [
                "SAFE",
                "SUSPICIOUS",
                "BLOCKED"
            ],
            "x-enum-comments": {
                "StatusBlocked": "\u003e= 76",
                "StatusSafe": "score \u003c= 50",
                "StatusSuspicious": "51-75"
            },
            "x-enum-descriptions": [
                "score \u003c= 50",
                "51-75",
                "\u003e= 76"
            ],
            "x-enum-varnames": [
                "StatusSafe",
                "StatusSuspicious",
                "StatusBlocked"
            ]
        },
        "internal_handler.BulkScanRequest": {
            "type": "object",
            "properties": {
                "urls": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "https://example.com",
                        "http://free-money-login.xyz/verify"
                    ]
                }
            }
        },
        "internal_handler.BulkScanResponse": {
            "type": "object",
            "properties": {
                "duration_ms": {
                    "type": "integer"
                },
                "results": {
                    "type": "array",
                    "items": {}
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "internal_handler.ErrorBody": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string",
                    "example": "INVALID_URL"
                },
                "message": {
                    "type": "string",
                    "example": "The provided URL is invalid"
                }
            }
        },
        "internal_handler.ErrorEnvelope": {
            "type": "object",
            "properties": {
                "error": {
                    "$ref": "#/definitions/internal_handler.ErrorBody"
                }
            }
        },
        "internal_handler.HealthResponse": {
            "type": "object",
            "properties": {
                "service": {
                    "type": "string",
                    "example": "goshield"
                },
                "status": {
                    "type": "string",
                    "example": "ok"
                },
                "version": {
                    "type": "string",
                    "example": "1.0.0"
                }
            }
        },
        "internal_handler.ListScansResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_neerajgurjar_goshield_backend_internal_model.Scan"
                    }
                },
                "pagination": {
                    "$ref": "#/definitions/internal_handler.Pagination"
                }
            }
        },
        "internal_handler.Pagination": {
            "type": "object",
            "properties": {
                "limit": {
                    "type": "integer"
                },
                "page": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                },
                "total_pages": {
                    "type": "integer"
                }
            }
        },
        "internal_handler.ScanRequest": {
            "type": "object",
            "properties": {
                "url": {
                    "type": "string",
                    "example": "http://free-money-login.xyz/verify"
                }
            }
        }
    },
    "tags": [
        {
            "description": "URL scanning and scan history",
            "name": "scans"
        },
        {
            "description": "Health and metrics",
            "name": "system"
        }
    ]
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{"http"},
	Title:            "GoShield API",
	Description:      "Offline URL security scanner. Every verdict is derived from the\nURL string alone: the service never sends traffic to the URL it is\nscanning, which keeps scans fast and rules out SSRF.\nScans are cached in Redis and stored in PostgreSQL.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
